#!/bin/sh

set -e

# temporary: download linaro-overlay packages, which provide
# auto-serial-console. Plans for the future include providing
# auto-serial-console in the Debian archive so we don't need this.
PREFIX=https://launchpad.net/~linaro-maintainers/+archive/overlay/+files
set -x
while read line; do
  if ! echo "$line" | sha1sum --check --quiet - > /dev/null 2>&1; then
    package=$(echo "$line" | awk '{ print($2) }')
    echo "Downloading $package ..."
    wget --quiet $PREFIX/$package
    echo "$line" | sha1sum --check --quiet
  fi
done < external-packages.sha1sum

set -x
sudo vmdebootstrap \
  --custom-package='linaro-overlay_1112.2_all.deb' \
  --custom-package='linaro-overlay-minimal_1112.2_all.deb' \
  --enable-dhcp \
  --serial-console --serial-console-command='/bin/auto-serial-console' \
  --root-password='root' \
  --verbose \
  "$@"
