#!/bin/bash
# shellcheck disable=SC2103
#
# Copyright (C) 2021 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#               2023 Michael Jeanson <mjeanson@efficios.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -exu

print_header() {
    set +x

    local message=" $1 "
    local message_len
    local padding_len

    message_len="${#message}"
    padding_len=$(( (80 - (message_len)) / 2 ))

    printf '\n'; printf -- '#%.0s' {1..80}; printf '\n'
    printf -- '-%.0s' {1..80}; printf '\n'
    printf -- '#%.0s' $(seq 1 $padding_len); printf '%s' "$message"; printf -- '#%.0s' $(seq 1 $padding_len); printf '\n'
    printf -- '-%.0s' {1..80}; printf '\n'
    printf -- '#%.0s' {1..80}; printf '\n\n'

    set -x
}

# Add ssh key for deployment
cp "$HOST_PUBLIC_KEYS" ~/.ssh/known_hosts
cp "$KEY_FILE_VARIABLE" ~/.ssh/id_rsa

export DEBIAN_FRONTEND=noninteractive
apt-get update

print_header "Install web tooling dependencies"
apt-get install -y jekyll npm grunt python3 python3-pip python3-venv linkchecker
export PYTHON_CONFIG=$(realpath python3-config)

print_header "Install babeltrace build dependencies"
apt-get install -y asciidoc xmlto libdw-dev libelf-dev elfutils autoconf automake libglib2.0-dev make doxygen flex bison

print_header "Install NPM stuff"
npm install

print_header "Install Python requirements"
python3 -m venv build_venv
source build_venv/bin/activate
pip install -r requirements.txt

# Setting TERM avoids spurious warnings when configure is checking TPUT, as
# $TERM is not set in the build environment.
# As we've already opened a venv, set SKIP_VENV so the python job doesn't
# create a second nested virtual environment.
print_header "Build website with grunt"
TERM=dumb SKIP_VENV=1 VERBOSE=1 grunt build:prod --verbose

print_header "Check links"
grunt connect:prod watch:prod &
SERVER_PID="${!}"
sleep 10 # While serve:prod starts up

OUTPUT_DIR="$(mktemp -d)"
OUTPUT_FILE="${OUTPUT_DIR}/linkchecker-out.csv"

# linkchecker drops privileges to 'nobody' when run as root
chown nobody "${OUTPUT_DIR}"

# @Note: Only internal links are checked by default
LINKCHECKER_ARGS=(
    '-q' '-F' "csv/utf-8/${OUTPUT_FILE}" '-f' '.linkcheckerrc'
    http://localhost:10000/
)
if ! linkchecker "${LINKCHECKER_ARGS[@]}" ; then
    echo "Linkchecker failed or found broken links"
    cat "${OUTPUT_FILE}"
    kill "${SERVER_PID}"
    rm -rf "${OUTPUT_DIR}"
    sleep 5 # Let serve:prod stop
    exit 1
else
    rm -rf "${OUTPUT_DIR}"
    kill "${SERVER_PID}"
fi

print_header "Deploy website"
grunt deploy:prod --verbose

# In the venv functions generated by the version of python installed on bionic
# nodes, the deactivate function checks undefined variables (eg. $1) which causes
# the build to fail when `set -u` is in effect.
set +u
deactivate

# EOF
