---
- hosts: hosts:!windows
  roles:
    # Setup filesystem and network configuration before other roles
    - zfs
    - netplan
- hosts: hosts
  roles:
    - common
- hosts: hosts:&incus:!windows
  roles:
    - incus
- hosts: hosts:!windows
  roles:
    - libvirt
    - rasdaemon
