---
- import_playbook: hosts.yml
- import_playbook: infra_lava.yml
- import_playbook: node_armhf.yml
- import_playbook: node_arm64.yml
- import_playbook: node_ppc64el.yml
- import_playbook: node_riscv64.yml
- import_playbook: node_s390x.yml
- import_playbook: node_i386.yml
- import_playbook: node_amd64.yml
- import_playbook: node_standalone.yml
- import_playbook: node_sles.yml
- import_playbook: node_el.yml
- hosts: node_yocto
  roles:
    - common
    - common-node
    - netplan
- hosts: gitmirror
  roles:
    - common
    - gitmirror
- hosts: jenkins
  roles:
    - common
    - jenkins
- hosts: ci_node:developer
  roles:
    - common
    - common-node
    - cross-compilers
    - compilers
    - babeltrace
    - binutils-gdb
    - librseq
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - libs-i386
- hosts: developer
  roles:
    - developer
    - docker
