---
cross_compilers_packages:
  - gcc-aarch64-linux-gnu
  - gcc-arm-linux-gnueabihf
  - gcc-i686-linux-gnu
  - gcc-powerpc64le-linux-gnu
  - gcc-powerpc-linux-gnu
  - gcc-riscv64-linux-gnu
  - gcc-s390x-linux-gnu

  - gcc-14-aarch64-linux-gnu
  - gcc-14-arm-linux-gnueabihf
  - gcc-14-i686-linux-gnu
  - gcc-14-powerpc64le-linux-gnu
  - gcc-14-powerpc-linux-gnu
  - gcc-14-riscv64-linux-gnu
  - gcc-14-s390x-linux-gnu

  - gcc-13-aarch64-linux-gnu
  - gcc-13-arm-linux-gnueabihf
  - gcc-13-i686-linux-gnu
  - gcc-13-powerpc64le-linux-gnu
  - gcc-13-powerpc-linux-gnu
  - gcc-13-riscv64-linux-gnu
  - gcc-13-s390x-linux-gnu

  - gcc-12-aarch64-linux-gnu
  - gcc-12-arm-linux-gnueabihf
  - gcc-12-i686-linux-gnu
  - gcc-12-powerpc64le-linux-gnu
  - gcc-12-powerpc-linux-gnu
  - gcc-12-riscv64-linux-gnu
  - gcc-12-s390x-linux-gnu

cross_compilers_packages_exclude_i386:
  - gcc-i686-linux-gnu
  - gcc-14-i686-linux-gnu
  - gcc-13-i686-linux-gnu
  - gcc-12-i686-linux-gnu
