---
netplan_manage: true
netplan_content: |
  network:
    version: 2
    renderer: networkd
    ethernets:
      enp1s0:
        dhcp4: no
        addresses:
          - 172.18.17.33/16
        routes:
          - to: default
            via: 172.18.0.1
        nameservers:
          search:
            - internal.efficios.com.
          addresses:
            - 172.18.0.13
