---
- hosts: all
  tasks:
    - when: ansible_os_family == 'Debian'
      ansible.builtin.command:
        argv: ['apt-get', 'clean']
    - when: ansible_os_family == 'Suse'
      ansible.builtin.command:
        argv: ['zypper', 'clean']
    - when: ansible_distribution == 'SLES'
      block:
        - ansible.builtin.command:
            argv: ['SUSEConnect', '-d']
        - ansible.builtin.command:
            argv: ['SUSEConnect', '--cleanup']
    - ansible.builtin.command:
        argv: ['cloud-init', 'clean']
      ignore_errors: true
    - ansible.builtin.command:
        argv: ['sync']
    - ansible.builtin.shell:
        cmd: 'history -cw'
      # Some default shells don't have the `history` built-in,
      # and it's not blocking that this works or not.
      ignore_errors: true
    - ansible.builtin.file:
        path: /root/.ssh/authorized_keys2
        state: absent
