---
common_node_packages:
  - autoconf
  - automake
  - bison
  - clang
  - curl
  - emacs-nox
  - flex
  - gcc
  - gcc-c++
  - gdb
  - gettext
  - git
  - htop
  - java-17-openjdk-devel
  - java-17-openjdk-headless
  - jq
  - libtool
  - lzop
  - make
  - openssh-server
  - openssl-devel
  - perl-Test-Harness
  - psmisc
  - python3-virtualenv
  - rsync
  - sudo
  - tree
  - vim
