---
common_node_patterns:
  - base
  - Minimal
  - Basis-Devel

common_node_packages:
  - autoconf
  - automake
  - bison
  - curl
  - flex
  - gdb
  - gettext-runtime
  - git-core
  - java-1_8_0-openjdk-devel
  - java-1_8_0-openjdk-headless
  - java-17-openjdk-headless
  - jq
  - libopenssl-devel
#  - libtap-harness-archive-perl
  - libtool
# - maven
  - openssh
  - psmisc
#  - python-virtualenv
  - python36
  - sudo
  - tree
  - vim

common_node_products:
  # for jq
  - PackageHub
