---
common_node_patterns:
  - base
  - Minimal
  - Basis-Devel

common_node_packages:
  - autoconf
  - automake
  - bison
  - curl
  - flex
  - gdb
  - gettext-runtime
  - git-core
  - java-1_8_0-openjdk-devel
  - java-1_8_0-openjdk-headless
  - java-11-openjdk-devel
  - java-11-openjdk-headless
#  - jq
  - libopenssl-devel
#  - libtap-harness-archive-perl
  - libtool
  - maven
  - openssh
  - psmisc
#  - python-virtualenv
  - sudo
  - tree
  - vim

# For SLES
common_node_products: []
